### ISSUE TITLE
Chat messages shouldn't use gendered pronouns

### ISSUE THREAD

**Issue by flarn2006** [LeonardoTheMutant/SRB2-Murder-Mystery#1]
I see a lot of messages referring to the sheriff and "his emerald". Can you please change this so it says "their emerald" instead? It makes me not want to play as the sheriff because I feel like the game is misgendering me.

**Comment by tedbasher** [comment]
sorry about this, it's just that leo isn't very good at english (no offense leo), it's not meant to be offensive on purpose

**Comment by LeonardoTheMutant** [comment]
I will try to edit the text so it will match all Genders. This change will likely affect all translations as well. I do agree that this is an Issue. When the text was creating there was no potential thought about female players. Sorry if this misunderstanding hurts you.

You can help us as well by editing the code contained in `SRC/LUA/INIT.LUA` where all the text with translations is located. Alternatively you can make an English **"patcher"** from `ASSETS/customlang.lua` file and we will add it into the base pack later

**Comment by tedbasher** [comment]
> You can help us as well by editing the code contained in [INIT.LUA](SRC/LUA/INIT.LUA) where all the text with translations is located. Alternatively you can make an English **"patcher"** from [this file](ASSETS/customlang.lua) and we will add it into the base pack later

i don't think this person was looking to fix it themselves, but yeah i suppose they could.
either way ill start reworking english, so..

**Comment by flarn2006** [comment]
Thank you for your understanding. I didn't think any offense was intended, and I appreciate you taking the time to address it.

**Comment by tedbasher** [comment]
I've just finished updating a lot of the English text, and have created a pull request.
I don't know if it will be accepted but I have created it.

**Comment by LeonardoTheMutant** [comment]
I think we finally finished with rewriting English. About 80% of the English text is remade from scratch and we tried our best to not use specific gender pronouns in it. Other language translations are going to be updated soon as well. Hope that the game will not encounter such misunderstandings ever again.

I should say thank you for pointing out this issue. I personally would never have though about that (not because I don't like other genders). Some testing and issues like that before release really help to prevent much more major problems in the future
